version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on: []
    command: python app.py
  # SQLite runs in-process, so no separate service needed
volumes:
  db_data: 